// <auto-generated />
namespace TestMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TestForTestMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestForTestMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202509300451228_TestForTestMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
